from qgis.PyQt import QtCore, QtGui, QtWidgets
from qgis.gui import QgsDockWidget

class Ui_QClassiPyDockWidget(object):
    def setupUi(self, QClassiPyDockWidget):
        QClassiPyDockWidget.setObjectName("QClassiPyDockWidget")
        QClassiPyDockWidget.resize(461, 539)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QClassiPyDockWidget.sizePolicy().hasHeightForWidth())
        QClassiPyDockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setMaximumSize(QtCore.QSize(461, 16777215))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.plugin_tabs = QtWidgets.QTabWidget(parent=self.dockWidgetContents)
        self.plugin_tabs.setGeometry(QtCore.QRect(9, 9, 443, 496))
        self.plugin_tabs.setMaximumSize(QtCore.QSize(443, 502))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plugin_tabs.setFont(font)
        self.plugin_tabs.setTabBarAutoHide(False)
        self.plugin_tabs.setObjectName("plugin_tabs")
        self.create_tiles_tab = QtWidgets.QWidget()
        self.create_tiles_tab.setObjectName("create_tiles_tab")
        self.plugin_tabs.addTab(self.create_tiles_tab, "")
        self.draw_mask_tab = QtWidgets.QWidget()
        self.draw_mask_tab.setObjectName("draw_mask_tab")
        self.plugin_tabs.addTab(self.draw_mask_tab, "")
        self.merge_mask_tab = QtWidgets.QWidget()
        self.merge_mask_tab.setObjectName("merge_mask_tab")
        self.plugin_tabs.addTab(self.merge_mask_tab, "")
        self.widget = QtWidgets.QWidget(parent=self.dockWidgetContents)
        self.widget.setGeometry(QtCore.QRect(335, 0, 120, 31))
        self.widget.setObjectName("widget")
        self.closing_label = QtWidgets.QLabel(parent=self.widget)
        self.closing_label.setGeometry(QtCore.QRect(25, 12, 71, 17))
        self.closing_label.setObjectName("closing_label")
        self.switching_label = QtWidgets.QLabel(parent=self.widget)
        self.switching_label.setGeometry(QtCore.QRect(20, 0, 81, 17))
        self.switching_label.setObjectName("switching_label")
        QClassiPyDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(QClassiPyDockWidget)
        self.plugin_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QClassiPyDockWidget)

    def retranslateUi(self, QClassiPyDockWidget):
        _translate = QtCore.QCoreApplication.translate
        QClassiPyDockWidget.setWindowTitle(_translate("QClassiPyDockWidget", "QClassiPy"))
        self.plugin_tabs.setTabText(self.plugin_tabs.indexOf(self.create_tiles_tab), _translate("QClassiPyDockWidget", "Create tiles"))
        self.plugin_tabs.setTabText(self.plugin_tabs.indexOf(self.draw_mask_tab), _translate("QClassiPyDockWidget", "Draw mask"))
        self.plugin_tabs.setTabText(self.plugin_tabs.indexOf(self.merge_mask_tab), _translate("QClassiPyDockWidget", "Merge masks"))
        self.closing_label.setText(_translate("QClassiPyDockWidget", "<html><head/><body><p><span style=\" color:#0002ff;\">Closing...</span></p></body></html>"))
        self.switching_label.setText(_translate("QClassiPyDockWidget", "<html><head/><body><p><span style=\" color:#0002ff;\">Switching...</span></p></body></html>"))





class Ui_QClassiPyCreateTiles(object):
    def setupUi(self, QClassiPyCreateTiles):
        QClassiPyCreateTiles.setObjectName("QClassiPyCreateTiles")
        QClassiPyCreateTiles.resize(434, 467)
        self.saved_message = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.saved_message.setGeometry(QtCore.QRect(375, 365, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.saved_message.setFont(font)
        self.saved_message.setObjectName("saved_message")
        self.tile_width = QtWidgets.QLineEdit(parent=QClassiPyCreateTiles)
        self.tile_width.setGeometry(QtCore.QRect(200, 405, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_width.setFont(font)
        self.tile_width.setObjectName("tile_width")
        self.raster_browse = QtWidgets.QToolButton(parent=QClassiPyCreateTiles)
        self.raster_browse.setGeometry(QtCore.QRect(330, 30, 28, 26))
        self.raster_browse.setObjectName("raster_browse")
        self.raster_err = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.raster_err.setGeometry(QtCore.QRect(210, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.raster_err.setFont(font)
        self.raster_err.setObjectName("raster_err")
        self.raster_choose = QtWidgets.QLineEdit(parent=QClassiPyCreateTiles)
        self.raster_choose.setGeometry(QtCore.QRect(10, 30, 321, 26))
        self.raster_choose.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.raster_choose.setText("")
        self.raster_choose.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.raster_choose.setObjectName("raster_choose")
        self.label_19 = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.label_19.setGeometry(QtCore.QRect(10, 365, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.raster_select = QtWidgets.QPushButton(parent=QClassiPyCreateTiles)
        self.raster_select.setGeometry(QtCore.QRect(370, 30, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.raster_select.setFont(font)
        self.raster_select.setAutoDefault(False)
        self.raster_select.setObjectName("raster_select")
        self.list_path_box = QtWidgets.QGroupBox(parent=QClassiPyCreateTiles)
        self.list_path_box.setGeometry(QtCore.QRect(10, 310, 411, 46))
        self.list_path_box.setCheckable(True)
        self.list_path_box.setObjectName("list_path_box")
        self.list_saveerr = QtWidgets.QLabel(parent=self.list_path_box)
        self.list_saveerr.setGeometry(QtCore.QRect(200, 0, 86, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.list_saveerr.setFont(font)
        self.list_saveerr.setObjectName("list_saveerr")
        self.list_save = QtWidgets.QLineEdit(parent=self.list_path_box)
        self.list_save.setGeometry(QtCore.QRect(0, 20, 384, 26))
        self.list_save.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.list_save.setText("")
        self.list_save.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.list_save.setObjectName("list_save")
        self.list_savebrowse = QtWidgets.QToolButton(parent=self.list_path_box)
        self.list_savebrowse.setGeometry(QtCore.QRect(383, 20, 28, 26))
        self.list_savebrowse.setObjectName("list_savebrowse")
        self.label_20 = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.label_20.setGeometry(QtCore.QRect(260, 365, 66, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.band_table = QtWidgets.QTableWidget(parent=QClassiPyCreateTiles)
        self.band_table.setGeometry(QtCore.QRect(10, 385, 91, 76))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.band_table.setFont(font)
        self.band_table.setObjectName("band_table")
        self.band_table.setColumnCount(1)
        self.band_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.band_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.band_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.band_table.setItem(0, 0, item)
        self.col_y_3 = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.col_y_3.setGeometry(QtCore.QRect(150, 410, 46, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.col_y_3.setFont(font)
        self.col_y_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.col_y_3.setObjectName("col_y_3")
        self.col_y_2 = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.col_y_2.setGeometry(QtCore.QRect(145, 437, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.col_y_2.setFont(font)
        self.col_y_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.col_y_2.setObjectName("col_y_2")
        self.band_add = QtWidgets.QToolButton(parent=QClassiPyCreateTiles)
        self.band_add.setGeometry(QtCore.QRect(110, 390, 16, 24))
        self.band_add.setObjectName("band_add")
        self.height_overlap = QtWidgets.QSpinBox(parent=QClassiPyCreateTiles)
        self.height_overlap.setGeometry(QtCore.QRect(270, 435, 44, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.height_overlap.setFont(font)
        self.height_overlap.setSuffix("")
        self.height_overlap.setProperty("value", 10)
        self.height_overlap.setObjectName("height_overlap")
        self.tile_height = QtWidgets.QLineEdit(parent=QClassiPyCreateTiles)
        self.tile_height.setGeometry(QtCore.QRect(200, 435, 51, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tile_height.setFont(font)
        self.tile_height.setObjectName("tile_height")
        self.label = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.label.setGeometry(QtCore.QRect(10, 10, 106, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.width_overlap = QtWidgets.QSpinBox(parent=QClassiPyCreateTiles)
        self.width_overlap.setGeometry(QtCore.QRect(270, 405, 44, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.width_overlap.setFont(font)
        self.width_overlap.setProperty("value", 10)
        self.width_overlap.setObjectName("width_overlap")
        self.bounds_box = QtWidgets.QGroupBox(parent=QClassiPyCreateTiles)
        self.bounds_box.setGeometry(QtCore.QRect(10, 60, 411, 186))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bounds_box.setFont(font)
        self.bounds_box.setObjectName("bounds_box")
        self.label_12 = QtWidgets.QLabel(parent=self.bounds_box)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 61, 17))
        self.label_12.setObjectName("label_12")
        self.topleft_y = QtWidgets.QLineEdit(parent=self.bounds_box)
        self.topleft_y.setGeometry(QtCore.QRect(110, 46, 51, 26))
        self.topleft_y.setText("")
        self.topleft_y.setCursorPosition(0)
        self.topleft_y.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.topleft_y.setObjectName("topleft_y")
        self.bottomright_y = QtWidgets.QLineEdit(parent=self.bounds_box)
        self.bottomright_y.setGeometry(QtCore.QRect(110, 79, 51, 26))
        self.bottomright_y.setObjectName("bottomright_y")
        self.label_13 = QtWidgets.QLabel(parent=self.bounds_box)
        self.label_13.setGeometry(QtCore.QRect(10, 78, 96, 26))
        self.label_13.setObjectName("label_13")
        self.col_y = QtWidgets.QLabel(parent=self.bounds_box)
        self.col_y.setGeometry(QtCore.QRect(110, 28, 51, 16))
        self.col_y.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.col_y.setObjectName("col_y")
        self.col_x = QtWidgets.QLabel(parent=self.bounds_box)
        self.col_x.setGeometry(QtCore.QRect(170, 28, 51, 16))
        self.col_x.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.col_x.setObjectName("col_x")
        self.pixel_bounds = QtWidgets.QRadioButton(parent=self.bounds_box)
        self.pixel_bounds.setGeometry(QtCore.QRect(95, 113, 61, 20))
        self.pixel_bounds.setChecked(True)
        self.pixel_bounds.setObjectName("pixel_bounds")
        self.raster_bounds = QtWidgets.QRadioButton(parent=self.bounds_box)
        self.raster_bounds.setGeometry(QtCore.QRect(95, 135, 81, 20))
        self.raster_bounds.setObjectName("raster_bounds")
        self.other_bounds = QtWidgets.QRadioButton(parent=self.bounds_box)
        self.other_bounds.setGeometry(QtCore.QRect(95, 158, 61, 20))
        self.other_bounds.setObjectName("other_bounds")
        self.label_14 = QtWidgets.QLabel(parent=self.bounds_box)
        self.label_14.setGeometry(QtCore.QRect(230, 28, 111, 17))
        self.label_14.setObjectName("label_14")
        self.crs_predef = QtWidgets.QPushButton(parent=self.bounds_box)
        self.crs_predef.setGeometry(QtCore.QRect(235, 46, 96, 26))
        self.crs_predef.setObjectName("crs_predef")
        self.topleft_x = QtWidgets.QLineEdit(parent=self.bounds_box)
        self.topleft_x.setGeometry(QtCore.QRect(170, 46, 51, 26))
        self.topleft_x.setObjectName("topleft_x")
        self.bottomright_x = QtWidgets.QLineEdit(parent=self.bounds_box)
        self.bottomright_x.setGeometry(QtCore.QRect(170, 79, 51, 26))
        self.bottomright_x.setObjectName("bottomright_x")
        self.label_18 = QtWidgets.QLabel(parent=self.bounds_box)
        self.label_18.setGeometry(QtCore.QRect(10, 135, 51, 16))
        self.label_18.setObjectName("label_18")
        self.crs_wkt = QtWidgets.QTextEdit(parent=self.bounds_box)
        self.crs_wkt.setGeometry(QtCore.QRect(229, 76, 176, 101))
        self.crs_wkt.setObjectName("crs_wkt")
        self.bounds_err = QtWidgets.QLabel(parent=self.bounds_box)
        self.bounds_err.setGeometry(QtCore.QRect(5, 28, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bounds_err.setFont(font)
        self.bounds_err.setWordWrap(True)
        self.bounds_err.setObjectName("bounds_err")
        self.crs_err = QtWidgets.QLabel(parent=self.bounds_box)
        self.crs_err.setGeometry(QtCore.QRect(350, 33, 51, 36))
        self.crs_err.setWordWrap(True)
        self.crs_err.setObjectName("crs_err")
        self.label_15 = QtWidgets.QLabel(parent=QClassiPyCreateTiles)
        self.label_15.setGeometry(QtCore.QRect(190, 365, 71, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.save_tiles = QtWidgets.QPushButton(parent=QClassiPyCreateTiles)
        self.save_tiles.setGeometry(QtCore.QRect(370, 385, 51, 76))
        self.save_tiles.setObjectName("save_tiles")
        self.mask_path_box = QtWidgets.QGroupBox(parent=QClassiPyCreateTiles)
        self.mask_path_box.setGeometry(QtCore.QRect(10, 255, 411, 46))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.mask_path_box.setFont(font)
        self.mask_path_box.setCheckable(True)
        self.mask_path_box.setObjectName("mask_path_box")
        self.mask_saveerr = QtWidgets.QLabel(parent=self.mask_path_box)
        self.mask_saveerr.setGeometry(QtCore.QRect(200, 0, 86, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mask_saveerr.sizePolicy().hasHeightForWidth())
        self.mask_saveerr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.mask_saveerr.setFont(font)
        self.mask_saveerr.setObjectName("mask_saveerr")
        self.mask_savebrowse = QtWidgets.QToolButton(parent=self.mask_path_box)
        self.mask_savebrowse.setGeometry(QtCore.QRect(383, 20, 28, 26))
        self.mask_savebrowse.setObjectName("mask_savebrowse")
        self.mask_save = QtWidgets.QLineEdit(parent=self.mask_path_box)
        self.mask_save.setGeometry(QtCore.QRect(0, 20, 384, 26))
        self.mask_save.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.mask_save.setText("")
        self.mask_save.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.mask_save.setObjectName("mask_save")
        self.band_rm = QtWidgets.QToolButton(parent=QClassiPyCreateTiles)
        self.band_rm.setGeometry(QtCore.QRect(110, 420, 16, 24))
        self.band_rm.setObjectName("band_rm")

        self.retranslateUi(QClassiPyCreateTiles)
        QtCore.QMetaObject.connectSlotsByName(QClassiPyCreateTiles)

    def retranslateUi(self, QClassiPyCreateTiles):
        _translate = QtCore.QCoreApplication.translate
        QClassiPyCreateTiles.setWindowTitle(_translate("QClassiPyCreateTiles", "Form"))
        self.saved_message.setText(_translate("QClassiPyCreateTiles", "<html><head/><body><p><span style=\" color:#0112fe;\">Saved</span></p></body></html>"))
        self.tile_width.setText(_translate("QClassiPyCreateTiles", "224"))
        self.raster_browse.setText(_translate("QClassiPyCreateTiles", "..."))
        self.raster_err.setText(_translate("QClassiPyCreateTiles", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid file</span></p></body></html>"))
        self.label_19.setText(_translate("QClassiPyCreateTiles", "Mask bands"))
        self.raster_select.setText(_translate("QClassiPyCreateTiles", "Select"))
        self.list_path_box.setTitle(_translate("QClassiPyCreateTiles", "Tile list path"))
        self.list_saveerr.setText(_translate("QClassiPyCreateTiles", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid path</span></p></body></html>"))
        self.list_savebrowse.setText(_translate("QClassiPyCreateTiles", "..."))
        self.label_20.setText(_translate("QClassiPyCreateTiles", "Over\n"
"lap (%)"))
        __sortingEnabled = self.band_table.isSortingEnabled()
        self.band_table.setSortingEnabled(False)
        item = self.band_table.item(0, 0)
        item.setText(_translate("QClassiPyCreateTiles", "mask"))
        self.band_table.setSortingEnabled(__sortingEnabled)
        self.col_y_3.setText(_translate("QClassiPyCreateTiles", "Width"))
        self.col_y_2.setText(_translate("QClassiPyCreateTiles", "Height"))
        self.band_add.setText(_translate("QClassiPyCreateTiles", "+"))
        self.tile_height.setText(_translate("QClassiPyCreateTiles", "224"))
        self.label.setText(_translate("QClassiPyCreateTiles", "Choose raster"))
        self.bounds_box.setTitle(_translate("QClassiPyCreateTiles", "Bounds"))
        self.label_12.setText(_translate("QClassiPyCreateTiles", "Top left"))
        self.label_13.setText(_translate("QClassiPyCreateTiles", "Bottom right"))
        self.col_y.setText(_translate("QClassiPyCreateTiles", "Y"))
        self.col_x.setText(_translate("QClassiPyCreateTiles", "X"))
        self.pixel_bounds.setText(_translate("QClassiPyCreateTiles", "Pixels"))
        self.raster_bounds.setText(_translate("QClassiPyCreateTiles", "Raster"))
        self.other_bounds.setText(_translate("QClassiPyCreateTiles", "Other "))
        self.label_14.setText(_translate("QClassiPyCreateTiles", "Other CRS WKT"))
        self.crs_predef.setText(_translate("QClassiPyCreateTiles", "Predefined"))
        self.label_18.setText(_translate("QClassiPyCreateTiles", "CRS"))
        self.bounds_err.setText(_translate("QClassiPyCreateTiles", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid bounds</span></p></body></html>"))
        self.crs_err.setText(_translate("QClassiPyCreateTiles", "<html><head/><body><p><span style=\" color:#ff0000;\">Invalid CRS</span></p></body></html>"))
        self.label_15.setText(_translate("QClassiPyCreateTiles", "Tile size \n"
"(px)"))
        self.save_tiles.setText(_translate("QClassiPyCreateTiles", "SAVE"))
        self.mask_path_box.setTitle(_translate("QClassiPyCreateTiles", "Mask path"))
        self.mask_saveerr.setText(_translate("QClassiPyCreateTiles", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid path</span></p></body></html>"))
        self.mask_savebrowse.setText(_translate("QClassiPyCreateTiles", "..."))
        self.band_rm.setText(_translate("QClassiPyCreateTiles", "-"))


class Ui_QClassiPyDrawMask(object):
    def setupUi(self, QClassiPyDrawMask):
        QClassiPyDrawMask.setObjectName("QClassiPyDrawMask")
        QClassiPyDrawMask.resize(434, 466)
        self.list_load_group = QtWidgets.QGroupBox(parent=QClassiPyDrawMask)
        self.list_load_group.setGeometry(QtCore.QRect(5, 120, 421, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.list_load_group.setFont(font)
        self.list_load_group.setCheckable(True)
        self.list_load_group.setChecked(True)
        self.list_load_group.setObjectName("list_load_group")
        self.list_browse = QtWidgets.QToolButton(parent=self.list_load_group)
        self.list_browse.setGeometry(QtCore.QRect(290, 30, 28, 26))
        self.list_browse.setObjectName("list_browse")
        self.list_load = QtWidgets.QLineEdit(parent=self.list_load_group)
        self.list_load.setGeometry(QtCore.QRect(10, 30, 281, 26))
        self.list_load.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.list_load.setText("")
        self.list_load.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.list_load.setObjectName("list_load")
        self.list_manual = QtWidgets.QPushButton(parent=self.list_load_group)
        self.list_manual.setGeometry(QtCore.QRect(325, 30, 91, 26))
        self.list_manual.setAutoDefault(False)
        self.list_manual.setObjectName("list_manual")
        self.list_err = QtWidgets.QLabel(parent=self.list_load_group)
        self.list_err.setGeometry(QtCore.QRect(150, 0, 71, 16))
        self.list_err.setObjectName("list_err")
        self.list_change_file = QtWidgets.QPushButton(parent=self.list_load_group)
        self.list_change_file.setGeometry(QtCore.QRect(152, 63, 130, 21))
        self.list_change_file.setAutoDefault(False)
        self.list_change_file.setObjectName("list_change_file")
        self.list_path_err = QtWidgets.QLabel(parent=self.list_load_group)
        self.list_path_err.setGeometry(QtCore.QRect(250, 0, 136, 16))
        self.list_path_err.setObjectName("list_path_err")
        self.classify_box = QtWidgets.QGroupBox(parent=QClassiPyDrawMask)
        self.classify_box.setGeometry(QtCore.QRect(5, 215, 421, 246))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.classify_box.setFont(font)
        self.classify_box.setCheckable(False)
        self.classify_box.setObjectName("classify_box")
        self.null_value_edit = QtWidgets.QLineEdit(parent=self.classify_box)
        self.null_value_edit.setGeometry(QtCore.QRect(105, 65, 48, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.null_value_edit.setFont(font)
        self.null_value_edit.setObjectName("null_value_edit")
        self.band_combo = QtWidgets.QComboBox(parent=self.classify_box)
        self.band_combo.setGeometry(QtCore.QRect(65, 30, 91, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.band_combo.setFont(font)
        self.band_combo.setObjectName("band_combo")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.classify_box)
        self.groupBox_2.setGeometry(QtCore.QRect(345, 60, 65, 141))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(33, 23, 26, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 115, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.opacity_slider = QtWidgets.QSlider(parent=self.groupBox_2)
        self.opacity_slider.setGeometry(QtCore.QRect(5, 25, 26, 106))
        self.opacity_slider.setMaximum(100)
        self.opacity_slider.setProperty("value", 40)
        self.opacity_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.opacity_slider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.opacity_slider.setObjectName("opacity_slider")
        self.groupBox = QtWidgets.QGroupBox(parent=self.classify_box)
        self.groupBox.setGeometry(QtCore.QRect(5, 105, 326, 136))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layer_erase = QtWidgets.QRadioButton(parent=self.groupBox)
        self.layer_erase.setGeometry(QtCore.QRect(105, 50, 66, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layer_erase.setFont(font)
        self.layer_erase.setObjectName("layer_erase")
        self.layer_poly = QtWidgets.QRadioButton(parent=self.groupBox)
        self.layer_poly.setGeometry(QtCore.QRect(10, 50, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layer_poly.setFont(font)
        self.layer_poly.setChecked(False)
        self.layer_poly.setObjectName("layer_poly")
        self.layer_brush = QtWidgets.QRadioButton(parent=self.groupBox)
        self.layer_brush.setGeometry(QtCore.QRect(105, 30, 66, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layer_brush.setFont(font)
        self.layer_brush.setChecked(False)
        self.layer_brush.setObjectName("layer_brush")
        self.layer_select = QtWidgets.QRadioButton(parent=self.groupBox)
        self.layer_select.setGeometry(QtCore.QRect(10, 30, 86, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.layer_select.setFont(font)
        self.layer_select.setChecked(True)
        self.layer_select.setObjectName("layer_select")
        self.save_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.save_button.setGeometry(QtCore.QRect(270, 30, 46, 96))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.draw_value_edit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.draw_value_edit.setGeometry(QtCore.QRect(127, 100, 41, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.draw_value_edit.setFont(font)
        self.draw_value_edit.setObjectName("draw_value_edit")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 75, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.draw_value_def = QtWidgets.QComboBox(parent=self.groupBox)
        self.draw_value_def.setGeometry(QtCore.QRect(10, 100, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.draw_value_def.setFont(font)
        self.draw_value_def.setEditable(True)
        self.draw_value_def.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.NoInsert)
        self.draw_value_def.setObjectName("draw_value_def")
        self.draw_value_color = QtWidgets.QToolButton(parent=self.groupBox)
        self.draw_value_color.setGeometry(QtCore.QRect(190, 100, 56, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.draw_value_color.setFont(font)
        self.draw_value_color.setObjectName("draw_value_color")
        self.frame = QtWidgets.QFrame(parent=self.groupBox)
        self.frame.setGeometry(QtCore.QRect(100, 30, 161, 46))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.brush_width = QtWidgets.QSpinBox(parent=self.frame)
        self.brush_width.setGeometry(QtCore.QRect(90, 10, 56, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.brush_width.setFont(font)
        self.brush_width.setMinimum(1)
        self.brush_width.setProperty("value", 1)
        self.brush_width.setObjectName("brush_width")
        self.layer_poly.raise_()
        self.layer_select.raise_()
        self.save_button.raise_()
        self.draw_value_edit.raise_()
        self.label_8.raise_()
        self.draw_value_def.raise_()
        self.draw_value_color.raise_()
        self.frame.raise_()
        self.layer_erase.raise_()
        self.layer_brush.raise_()
        self.label_3 = QtWidgets.QLabel(parent=self.classify_box)
        self.label_3.setGeometry(QtCore.QRect(10, 35, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.classify_box)
        self.label_2.setGeometry(QtCore.QRect(10, 61, 76, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.classify_box)
        self.frame_2.setGeometry(QtCore.QRect(165, 30, 166, 75))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.rm_draw_value = QtWidgets.QPushButton(parent=self.frame_2)
        self.rm_draw_value.setGeometry(QtCore.QRect(30, 5, 106, 21))
        self.rm_draw_value.setObjectName("rm_draw_value")
        self.rm_larger = QtWidgets.QRadioButton(parent=self.frame_2)
        self.rm_larger.setGeometry(QtCore.QRect(90, 50, 76, 23))
        self.rm_larger.setObjectName("rm_larger")
        self.rm_current = QtWidgets.QRadioButton(parent=self.frame_2)
        self.rm_current.setGeometry(QtCore.QRect(5, 30, 76, 23))
        self.rm_current.setChecked(True)
        self.rm_current.setObjectName("rm_current")
        self.rm_absent = QtWidgets.QRadioButton(parent=self.frame_2)
        self.rm_absent.setGeometry(QtCore.QRect(5, 50, 76, 23))
        self.rm_absent.setObjectName("rm_absent")
        self.rm_others = QtWidgets.QRadioButton(parent=self.frame_2)
        self.rm_others.setGeometry(QtCore.QRect(90, 30, 76, 23))
        self.rm_others.setChecked(False)
        self.rm_others.setObjectName("rm_others")
        self.img_load_group = QtWidgets.QGroupBox(parent=QClassiPyDrawMask)
        self.img_load_group.setGeometry(QtCore.QRect(5, 10, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.img_load_group.setFont(font)
        self.img_load_group.setCheckable(False)
        self.img_load_group.setObjectName("img_load_group")
        self.img_browse = QtWidgets.QToolButton(parent=self.img_load_group)
        self.img_browse.setGeometry(QtCore.QRect(330, 30, 28, 26))
        self.img_browse.setObjectName("img_browse")
        self.img_fileload = QtWidgets.QLineEdit(parent=self.img_load_group)
        self.img_fileload.setGeometry(QtCore.QRect(10, 30, 321, 26))
        self.img_fileload.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.img_fileload.setText("")
        self.img_fileload.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.img_fileload.setObjectName("img_fileload")
        self.img_select = QtWidgets.QPushButton(parent=self.img_load_group)
        self.img_select.setGeometry(QtCore.QRect(365, 30, 51, 26))
        self.img_select.setAutoDefault(False)
        self.img_select.setObjectName("img_select")
        self.label_4 = QtWidgets.QLabel(parent=self.img_load_group)
        self.label_4.setGeometry(QtCore.QRect(20, 68, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.img_X_edit = QtWidgets.QLineEdit(parent=self.img_load_group)
        self.img_X_edit.setGeometry(QtCore.QRect(35, 65, 48, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.img_X_edit.setFont(font)
        self.img_X_edit.setText("")
        self.img_X_edit.setObjectName("img_X_edit")
        self.img_Y_edit = QtWidgets.QLineEdit(parent=self.img_load_group)
        self.img_Y_edit.setGeometry(QtCore.QRect(110, 65, 48, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.img_Y_edit.setFont(font)
        self.img_Y_edit.setText("")
        self.img_Y_edit.setObjectName("img_Y_edit")
        self.label_9 = QtWidgets.QLabel(parent=self.img_load_group)
        self.label_9.setGeometry(QtCore.QRect(95, 68, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.img_width_edit = QtWidgets.QLineEdit(parent=self.img_load_group)
        self.img_width_edit.setGeometry(QtCore.QRect(225, 65, 48, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.img_width_edit.setFont(font)
        self.img_width_edit.setText("")
        self.img_width_edit.setObjectName("img_width_edit")
        self.img_height_edit = QtWidgets.QLineEdit(parent=self.img_load_group)
        self.img_height_edit.setGeometry(QtCore.QRect(335, 65, 48, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.img_height_edit.setFont(font)
        self.img_height_edit.setText("")
        self.img_height_edit.setObjectName("img_height_edit")
        self.label_10 = QtWidgets.QLabel(parent=self.img_load_group)
        self.label_10.setGeometry(QtCore.QRect(180, 68, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.img_load_group)
        self.label_11.setGeometry(QtCore.QRect(285, 68, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.file_err = QtWidgets.QLabel(parent=self.img_load_group)
        self.file_err.setGeometry(QtCore.QRect(140, 0, 76, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.file_err.setFont(font)
        self.file_err.setObjectName("file_err")
        self.coord_err = QtWidgets.QLabel(parent=self.img_load_group)
        self.coord_err.setGeometry(QtCore.QRect(230, 0, 96, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.coord_err.setFont(font)
        self.coord_err.setObjectName("coord_err")

        self.retranslateUi(QClassiPyDrawMask)
        QtCore.QMetaObject.connectSlotsByName(QClassiPyDrawMask)

    def retranslateUi(self, QClassiPyDrawMask):
        _translate = QtCore.QCoreApplication.translate
        QClassiPyDrawMask.setWindowTitle(_translate("QClassiPyDrawMask", "Form"))
        self.list_load_group.setTitle(_translate("QClassiPyDrawMask", "Load tile list"))
        self.list_browse.setText(_translate("QClassiPyDrawMask", "..."))
        self.list_manual.setText(_translate("QClassiPyDrawMask", "Choose tile"))
        self.list_err.setText(_translate("QClassiPyDrawMask", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid list</span></p></body></html>"))
        self.list_change_file.setText(_translate("QClassiPyDrawMask", "Update mask path"))
        self.list_path_err.setText(_translate("QClassiPyDrawMask", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid mask path</span></p></body></html>"))
        self.classify_box.setTitle(_translate("QClassiPyDrawMask", "Classify"))
        self.null_value_edit.setText(_translate("QClassiPyDrawMask", "0"))
        self.groupBox_2.setTitle(_translate("QClassiPyDrawMask", "Opacity"))
        self.label_6.setText(_translate("QClassiPyDrawMask", "<html><head/><body><p align=\"center\">100</p></body></html>"))
        self.label_5.setText(_translate("QClassiPyDrawMask", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.groupBox.setTitle(_translate("QClassiPyDrawMask", "Tools"))
        self.layer_erase.setText(_translate("QClassiPyDrawMask", "Erase"))
        self.layer_poly.setText(_translate("QClassiPyDrawMask", "Polygons"))
        self.layer_brush.setText(_translate("QClassiPyDrawMask", "Brush"))
        self.layer_select.setText(_translate("QClassiPyDrawMask", "Selection"))
        self.save_button.setText(_translate("QClassiPyDrawMask", "SAVE"))
        self.draw_value_edit.setText(_translate("QClassiPyDrawMask", "1"))
        self.label_8.setText(_translate("QClassiPyDrawMask", "Draw value"))
        self.draw_value_color.setText(_translate("QClassiPyDrawMask", "Color"))
        self.label_3.setText(_translate("QClassiPyDrawMask", "Band"))
        self.label_2.setText(_translate("QClassiPyDrawMask", "Null value"))
        self.rm_draw_value.setText(_translate("QClassiPyDrawMask", "Remove class"))
        self.rm_larger.setText(_translate("QClassiPyDrawMask", "Larger"))
        self.rm_current.setText(_translate("QClassiPyDrawMask", "Current"))
        self.rm_absent.setText(_translate("QClassiPyDrawMask", "Absent"))
        self.rm_others.setText(_translate("QClassiPyDrawMask", "Others"))
        self.img_load_group.setTitle(_translate("QClassiPyDrawMask", "Load image"))
        self.img_browse.setText(_translate("QClassiPyDrawMask", "..."))
        self.img_select.setText(_translate("QClassiPyDrawMask", "Select"))
        self.label_4.setText(_translate("QClassiPyDrawMask", "X"))
        self.label_9.setText(_translate("QClassiPyDrawMask", "Y"))
        self.label_10.setText(_translate("QClassiPyDrawMask", "Width"))
        self.label_11.setText(_translate("QClassiPyDrawMask", "Height"))
        self.file_err.setText(_translate("QClassiPyDrawMask", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid file</span></p></body></html>"))
        self.coord_err.setText(_translate("QClassiPyDrawMask", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid coords</span></p></body></html>"))



class Ui_QClassiPyMergeMasks(object):
    def setupUi(self, QClassiPyMergeMasks):
        QClassiPyMergeMasks.setObjectName("QClassiPyMergeMasks")
        QClassiPyMergeMasks.resize(434, 467)
        self.list1_group = QtWidgets.QGroupBox(parent=QClassiPyMergeMasks)
        self.list1_group.setGeometry(QtCore.QRect(5, 15, 426, 96))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.list1_group.setFont(font)
        self.list1_group.setCheckable(False)
        self.list1_group.setChecked(False)
        self.list1_group.setObjectName("list1_group")
        self.list1_browse = QtWidgets.QToolButton(parent=self.list1_group)
        self.list1_browse.setGeometry(QtCore.QRect(255, 30, 28, 26))
        self.list1_browse.setObjectName("list1_browse")
        self.list1_load = QtWidgets.QLineEdit(parent=self.list1_group)
        self.list1_load.setGeometry(QtCore.QRect(55, 30, 201, 26))
        self.list1_load.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.list1_load.setText("")
        self.list1_load.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.list1_load.setObjectName("list1_load")
        self.list1_err = QtWidgets.QLabel(parent=self.list1_group)
        self.list1_err.setGeometry(QtCore.QRect(175, 0, 96, 16))
        self.list1_err.setObjectName("list1_err")
        self.list1_change_file = QtWidgets.QPushButton(parent=self.list1_group)
        self.list1_change_file.setGeometry(QtCore.QRect(290, 30, 131, 26))
        self.list1_change_file.setAutoDefault(False)
        self.list1_change_file.setObjectName("list1_change_file")
        self.list2_err = QtWidgets.QLabel(parent=self.list1_group)
        self.list2_err.setGeometry(QtCore.QRect(280, 0, 91, 16))
        self.list2_err.setObjectName("list2_err")
        self.label_3 = QtWidgets.QLabel(parent=self.list1_group)
        self.label_3.setGeometry(QtCore.QRect(10, 35, 41, 17))
        self.label_3.setObjectName("label_3")
        self.list2_browse = QtWidgets.QToolButton(parent=self.list1_group)
        self.list2_browse.setGeometry(QtCore.QRect(255, 60, 28, 26))
        self.list2_browse.setObjectName("list2_browse")
        self.label_4 = QtWidgets.QLabel(parent=self.list1_group)
        self.label_4.setGeometry(QtCore.QRect(10, 65, 41, 17))
        self.label_4.setObjectName("label_4")
        self.list2_change_file = QtWidgets.QPushButton(parent=self.list1_group)
        self.list2_change_file.setGeometry(QtCore.QRect(290, 60, 131, 26))
        self.list2_change_file.setAutoDefault(False)
        self.list2_change_file.setObjectName("list2_change_file")
        self.list2_load = QtWidgets.QLineEdit(parent=self.list1_group)
        self.list2_load.setGeometry(QtCore.QRect(55, 60, 201, 26))
        self.list2_load.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.list2_load.setText("")
        self.list2_load.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.list2_load.setObjectName("list2_load")
        self.list1_group_2 = QtWidgets.QGroupBox(parent=QClassiPyMergeMasks)
        self.list1_group_2.setGeometry(QtCore.QRect(5, 120, 426, 96))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.list1_group_2.setFont(font)
        self.list1_group_2.setCheckable(False)
        self.list1_group_2.setChecked(False)
        self.list1_group_2.setObjectName("list1_group_2")
        self.list_savebrowse = QtWidgets.QToolButton(parent=self.list1_group_2)
        self.list_savebrowse.setGeometry(QtCore.QRect(385, 30, 28, 26))
        self.list_savebrowse.setObjectName("list_savebrowse")
        self.list_save = QtWidgets.QLineEdit(parent=self.list1_group_2)
        self.list_save.setGeometry(QtCore.QRect(70, 30, 316, 26))
        self.list_save.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.list_save.setText("")
        self.list_save.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.list_save.setObjectName("list_save")
        self.label_5 = QtWidgets.QLabel(parent=self.list1_group_2)
        self.label_5.setGeometry(QtCore.QRect(10, 35, 51, 17))
        self.label_5.setObjectName("label_5")
        self.mask_savebrowse = QtWidgets.QToolButton(parent=self.list1_group_2)
        self.mask_savebrowse.setGeometry(QtCore.QRect(385, 60, 28, 26))
        self.mask_savebrowse.setObjectName("mask_savebrowse")
        self.label_6 = QtWidgets.QLabel(parent=self.list1_group_2)
        self.label_6.setGeometry(QtCore.QRect(10, 65, 41, 17))
        self.label_6.setObjectName("label_6")
        self.mask_save = QtWidgets.QLineEdit(parent=self.list1_group_2)
        self.mask_save.setGeometry(QtCore.QRect(70, 60, 316, 26))
        self.mask_save.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.mask_save.setText("")
        self.mask_save.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.mask_save.setObjectName("mask_save")
        self.mask_saveerr = QtWidgets.QLabel(parent=self.list1_group_2)
        self.mask_saveerr.setGeometry(QtCore.QRect(135, 0, 126, 16))
        self.mask_saveerr.setObjectName("mask_saveerr")
        self.list_saveerr = QtWidgets.QLabel(parent=self.list1_group_2)
        self.list_saveerr.setGeometry(QtCore.QRect(275, 0, 126, 16))
        self.list_saveerr.setObjectName("list_saveerr")
        self.merge_button = QtWidgets.QPushButton(parent=QClassiPyMergeMasks)
        self.merge_button.setGeometry(QtCore.QRect(175, 225, 89, 51))
        self.merge_button.setObjectName("merge_button")
        self.tile_err = QtWidgets.QLabel(parent=QClassiPyMergeMasks)
        self.tile_err.setGeometry(QtCore.QRect(310, 220, 111, 56))
        self.tile_err.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tile_err.setWordWrap(True)
        self.tile_err.setObjectName("tile_err")
        self.shape_err = QtWidgets.QLabel(parent=QClassiPyMergeMasks)
        self.shape_err.setGeometry(QtCore.QRect(10, 220, 136, 56))
        self.shape_err.setWordWrap(True)
        self.shape_err.setObjectName("shape_err")
        self.label = QtWidgets.QLabel(parent=QClassiPyMergeMasks)
        self.label.setGeometry(QtCore.QRect(45, 300, 341, 46))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.merged_message = QtWidgets.QLabel(parent=QClassiPyMergeMasks)
        self.merged_message.setGeometry(QtCore.QRect(192, 280, 56, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.merged_message.setFont(font)
        self.merged_message.setObjectName("merged_message")

        self.retranslateUi(QClassiPyMergeMasks)
        QtCore.QMetaObject.connectSlotsByName(QClassiPyMergeMasks)

    def retranslateUi(self, QClassiPyMergeMasks):
        _translate = QtCore.QCoreApplication.translate
        QClassiPyMergeMasks.setWindowTitle(_translate("QClassiPyMergeMasks", "Form"))
        self.list1_group.setTitle(_translate("QClassiPyMergeMasks", "Input tile lists"))
        self.list1_browse.setText(_translate("QClassiPyMergeMasks", "..."))
        self.list1_err.setText(_translate("QClassiPyMergeMasks", "<html><head/><body><p><span style=\" color:#e01b24;\">List 1 invalid</span></p></body></html>"))
        self.list1_change_file.setText(_translate("QClassiPyMergeMasks", "Update mask path"))
        self.list2_err.setText(_translate("QClassiPyMergeMasks", "<html><head/><body><p><span style=\" color:#e01b24;\">List 2 invalid</span></p></body></html>"))
        self.label_3.setText(_translate("QClassiPyMergeMasks", "List 1"))
        self.list2_browse.setText(_translate("QClassiPyMergeMasks", "..."))
        self.label_4.setText(_translate("QClassiPyMergeMasks", "List 2"))
        self.list2_change_file.setText(_translate("QClassiPyMergeMasks", "Update mask path"))
        self.list1_group_2.setTitle(_translate("QClassiPyMergeMasks", "Merged outputs"))
        self.list_savebrowse.setText(_translate("QClassiPyMergeMasks", "..."))
        self.label_5.setText(_translate("QClassiPyMergeMasks", "Tile list"))
        self.mask_savebrowse.setText(_translate("QClassiPyMergeMasks", "..."))
        self.label_6.setText(_translate("QClassiPyMergeMasks", "Mask"))
        self.mask_saveerr.setText(_translate("QClassiPyMergeMasks", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid mask path</span></p></body></html>"))
        self.list_saveerr.setText(_translate("QClassiPyMergeMasks", "<html><head/><body><p><span style=\" color:#e01b24;\">Invalid list path</span></p></body></html>"))
        self.merge_button.setText(_translate("QClassiPyMergeMasks", "MERGE"))
        self.tile_err.setText(_translate("QClassiPyMergeMasks", "<html><head/><body><p><span style=\" color:#e01b24;\">Lists don\'t have the same tiles</span></p></body></html>"))
        self.shape_err.setText(_translate("QClassiPyMergeMasks", "<html><head/><body><p><span style=\" color:#e01b24;\">Masks do not have the same shape or type</span></p></body></html>"))
        self.label.setText(_translate("QClassiPyMergeMasks", "In case of overlaps, priority will be given to list 1."))
        self.merged_message.setText(_translate("QClassiPyMergeMasks", "<html><head/><body><p><span style=\" color:#0112fe;\">Merged</span></p></body></html>"))



class Ui_TableDock(object):
    def setupUi(self, TableDock):
        TableDock.setObjectName("TableDock")
        TableDock.resize(463, 303)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TableDock.sizePolicy().hasHeightForWidth())
        TableDock.setSizePolicy(sizePolicy)
        TableDock.setMinimumSize(QtCore.QSize(171, 303))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.dockWidgetContents)
        self.buttonBox.setGeometry(QtCore.QRect(5, 5, 171, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.list_table = QtWidgets.QTableWidget(parent=self.dockWidgetContents)
        self.list_table.setGeometry(QtCore.QRect(0, 35, 461, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_table.sizePolicy().hasHeightForWidth())
        self.list_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.list_table.setFont(font)
        self.list_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.list_table.setWordWrap(False)
        self.list_table.setObjectName("list_table")
        self.list_table.setColumnCount(0)
        self.list_table.setRowCount(0)
        TableDock.setWidget(self.dockWidgetContents)

        self.retranslateUi(TableDock)
        QtCore.QMetaObject.connectSlotsByName(TableDock)

    def retranslateUi(self, TableDock):
        _translate = QtCore.QCoreApplication.translate
        TableDock.setWindowTitle(_translate("TableDock", "Tile list"))
